

INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS,PASSWORD,PROFILE_PIC_URL) VALUES ('ahmad', 'ali', 'g1@g1.com','123','/assest/1.png');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS,PASSWORD,PROFILE_PIC_URL) VALUES ('ahmad', 'mhmod', 'g2@g1.com','777','assest/2.png');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS,PASSWORD,PROFILE_PIC_URL) VALUES ('ramz', 'kj', 'g3@g1.com','456','assest/3.png');



INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g1@g1.com'), '2021-01-01','post1','this is content post1 for ahmad');
INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g1@g1.com'), '2021-02-01','post2','this is content post2 for ahmad');
INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g1@g1.com'), '2021-03-01','post3','this is content post3 for ahmad');

INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g3@g1.com'), '2022-01-01','post4','this is content post1 for ramz');
INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g3@g1.com'), '2022-02-01','post5','this is content post2 for ramz');
INSERT INTO POST (USER_ID, POSTED_AT,TITLE,CONTENT) VALUES ((SELECT ID FROM USER WHERE EMAIL_ADDRESS = 'g3@g1.com'), '2022-03-01','post6','this is content post3 for ramz');
