CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64) UNIQUE  NOT NULL,
  PROFILE_PIC_URL VARCHAR(200),
  PASSWORD VARCHAR(64) NOT NULL
  
);



CREATE TABLE POST(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  POSTED_AT DATETIME NOT NULL,
  TITLE VARCHAR(100) NOT NULL, 
  CONTENT         VARCHAR(1000),
  USER_ID  BIGINT NOT NULL
  
);

ALTER TABLE POST ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID);







